### ISSUE TITLE
Index Event Calendar

### ISSUE THREAD

**Issue by anshaik** [architechs/dfwinnovationcenter#5]
Need some sort of calendar support. Maybe do something with MeetUp and see if they have support? Otherwise just something else for now.

**Comment by bearcott** [comment]
Where would the calender go?

**Comment by anshaik** [comment]
Here:

	 		<div class="col-lg-3">
	 			<h4>Event Calendar</h4>
	 			<div class="hline"></div>
	 			<p>Calendar here</a></p>

**Comment by bearcott** [comment]
I've added a plugin called `full calender` which can be integrated into google calendar given an API key.
