### ISSUE TITLE
owl-carousel symbols

### ISSUE THREAD

**Issue by anshaik** [architechs/dfwinnovationcenter#7]
Pick a representative symbol for forum

**Comment by bearcott** [comment]
I dont know what you mean?

**Comment by anshaik** [comment]
I wanted to add a symbol for each "owl-example" item. Example:

 
	 					<i class="fa fa-trophy"></i>

Instead of the trophy, some representative symbol for each header. i.e. IEEE logo for IEEE forums. I might have to think these up, but if you have an idea you can add them in.

**Comment by bearcott** [comment]
I'm afraid I'm not too sure what the associations are between these names. I think it would be best if you figured out what to put there.
