### ISSUE TITLE
Need a logo for "DFW Innovation Center" in index

### ISSUE THREAD

**Issue by anshaik** [architechs/dfwinnovationcenter#8]
Need logo for:

<h1>DFW Innovation Center</h1> 

![dfwic_logo](https://cloud.githubusercontent.com/assets/4521095/7558404/25b646c8-f769-11e4-8d92-45dc812e6859.jpg)

Above as inspiration.

**Comment by bearcott** [comment]
![dfw](https://cloud.githubusercontent.com/assets/3137126/7580029/0f413c5c-f833-11e4-8089-118878fdd0dc.png)
